import {
  Beef, Beer, CakeSlice, Coffee, CupSoda, Flame, House, Leaf, Package,
  Pizza, Popcorn, Star, Tag, Sandwich, IceCream, Wine,
  Cherry, Apple, Croissant, Egg, Fish,
  Cookie, Milk, GlassWater, Citrus, Wheat, UtensilsCrossed, ChefHat,
  Grape, Candy, Martini, ShoppingBag, Heart, Sparkles,
  Zap, Crown, Gift, Percent, Clock, ThumbsUp, Ban,
  Salad, Soup, Ham, Drumstick, Banana, Carrot,
  Dessert, Cake, Donut, Lollipop, Popsicle,
  Amphora, Baby, Droplets, Glasses, CircleDot,
  Truck, Bike, MapPin, Phone, MessageCircle,
  Receipt, Wallet, CreditCard, DollarSign, BadgePercent,
  Music, Tv, Wifi, Sun, Moon, CloudSun, Snowflake,
  Utensils, Store, Building2, Printer, QrCode,
  Users, UserCheck, Shield, Bell, AlertTriangle,
  Leaf as LeafAlt, TreePine, Flower2, Sprout,
} from "lucide-react";

const iconMap: Record<string, React.FC<{ className?: string }>> = {
  house: House,
  home: House,
  beef: Beef,
  burger: Sandwich,
  popcorn: Popcorn,
  "cup-soda": CupSoda,
  "cake-slice": CakeSlice,
  cake: Cake,
  package: Package,
  box: Package,
  flame: Flame,
  pizza: Pizza,
  coffee: Coffee,
  beer: Beer,
  star: Star,
  leaf: Leaf,
  tag: Tag,
  "ice-cream": IceCream,
  wine: Wine,
  cherry: Cherry,
  apple: Apple,
  croissant: Croissant,
  egg: Egg,
  fish: Fish,
  cookie: Cookie,
  milk: Milk,
  "glass-water": GlassWater,
  citrus: Citrus,
  wheat: Wheat,
  utensils: UtensilsCrossed,
  "chef-hat": ChefHat,
  grape: Grape,
  candy: Candy,
  martini: Martini,
  "shopping-bag": ShoppingBag,
  heart: Heart,
  sparkles: Sparkles,
  zap: Zap,
  crown: Crown,
  gift: Gift,
  percent: Percent,
  clock: Clock,
  "thumbs-up": ThumbsUp,
  ban: Ban,
  // New icons
  salad: Salad,
  soup: Soup,
  ham: Ham,
  drumstick: Drumstick,
  banana: Banana,
  carrot: Carrot,
  dessert: Dessert,
  donut: Donut,
  lollipop: Lollipop,
  popsicle: Popsicle,
  amphora: Amphora,
  baby: Baby,
  droplets: Droplets,
  glasses: Glasses,
  "circle-dot": CircleDot,
  truck: Truck,
  bike: Bike,
  "map-pin": MapPin,
  phone: Phone,
  "message-circle": MessageCircle,
  receipt: Receipt,
  wallet: Wallet,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  "badge-percent": BadgePercent,
  music: Music,
  tv: Tv,
  wifi: Wifi,
  sun: Sun,
  moon: Moon,
  "cloud-sun": CloudSun,
  snowflake: Snowflake,
  "utensils-crossed": Utensils,
  store: Store,
  building: Building2,
  printer: Printer,
  "qr-code": QrCode,
  users: Users,
  "user-check": UserCheck,
  shield: Shield,
  bell: Bell,
  alert: AlertTriangle,
  "tree-pine": TreePine,
  flower: Flower2,
  sprout: Sprout,
};

export const availableIcons = Object.keys(iconMap);

export const iconGroups = [
  { label: "Comidas", icons: ["burger", "pizza", "beef", "fish", "egg", "croissant", "wheat", "flame", "salad", "soup", "ham", "drumstick", "carrot"] },
  { label: "Doces & Sobremesas", icons: ["cake", "cake-slice", "cookie", "candy", "ice-cream", "cherry", "grape", "dessert", "donut", "lollipop", "popsicle"] },
  { label: "Bebidas", icons: ["coffee", "beer", "wine", "martini", "cup-soda", "milk", "glass-water", "citrus", "droplets", "amphora"] },
  { label: "Frutas & Naturais", icons: ["apple", "banana", "cherry", "grape", "citrus", "leaf", "tree-pine", "flower", "sprout"] },
  { label: "Delivery & Serviço", icons: ["truck", "bike", "map-pin", "phone", "message-circle", "receipt", "wallet", "credit-card", "dollar-sign", "badge-percent"] },
  { label: "Especiais", icons: ["star", "sparkles", "crown", "heart", "gift", "percent", "zap", "thumbs-up", "clock", "sun", "moon", "snowflake", "cloud-sun"] },
  { label: "Outros", icons: ["utensils", "chef-hat", "shopping-bag", "box", "tag", "popcorn", "ban", "store", "building", "bell", "shield", "users", "music", "tv", "wifi", "glasses", "baby"] },
];

interface Props {
  name: string;
  className?: string;
}

const CategoryIcon = ({ name, className = "w-5 h-5" }: Props) => {
  const Icon = iconMap[name];
  if (!Icon) return <Tag className={className} />;
  return <Icon className={className} />;
};

export default CategoryIcon;
