
-- Enable RLS on ALL public tables that don't have it yet
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fechamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eventos_operacionais ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimentacoes_caixa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estado_caixa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estado_mesas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_license ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.master_despesas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bairros_delivery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes_delivery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.module_pins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mesas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tablets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.motoboys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.motoboy_fechamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preferencias_operacionais ENABLE ROW LEVEL SECURITY;
