// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtroaobjlvgprarcubfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cm9hb2JqbHZncHJhcmN1YmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzODE5NDIsImV4cCI6MjA4OTk1Nzk0Mn0.ZJlXyjpt7C1pGxCBT_yHc10e7iJKLi41e8l8cUQIQ3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});